async function W4(x,A,D,k,M){
  const fail=(msg)=>({score:0,feedback:msg,classification:"Needs improvement",toneScore:0,toneFeedback:"Insufficient pitch information to assess the tone contour.",segmentalScore:0,segmentalFeedback:"Insufficient segmental information to compare the initial and final.",articulationScore:0,articulationFeedback:"A clearer recording is required to assess articulation and tongue placement.",fluencyScore:0,fluencyFeedback:"Insufficient signal to assess fluency.",details:[]});
  let ctx=null;
  try{
    const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return fail("This browser does not support local audio analysis.");const started=performance.now();ctx=new AC();
    const bytes=async(src)=>{if(!src||typeof src!=="string")return null;try{const cache=window.__PINYIN_AUDIO_BYTES_CACHE__||(window.__PINYIN_AUDIO_BYTES_CACHE__={});if(!cache[src])cache[src]=fetch(src).then(r=>{if(!r.ok)throw new Error("audio");return r.arrayBuffer()});const b=await cache[src];return b.slice(0)}catch{return null}};
    const decode=async(src)=>{const b=await bytes(src);return b?await ctx.decodeAudioData(b):null};const fastDecode=async(src,ms=1800)=>Promise.race([decode(src),new Promise(resolve=>setTimeout(()=>resolve(null),ms))]);
    const mono=(b)=>{const s=new Float32Array(b.length);for(let i=0;i<b.length;i++){let v=0;for(let c=0;c<b.numberOfChannels;c++)v+=b.getChannelData(c)[i];s[i]=v/Math.max(1,b.numberOfChannels)}return s};
    const basic=(s,sr)=>{let peak=0,e=0;for(const v of s){peak=Math.max(peak,Math.abs(v));e+=v*v}return{peak,rms:Math.sqrt(e/Math.max(1,s.length)),duration:s.length/sr}};
    // More sensitive speech capture: keep soft consonants and low-volume phones instead of trimming them away.
    const trim=(s,peak)=>{const gate=Math.max(.0035,peak*.065);let a=0,b=s.length-1;while(a<s.length&&Math.abs(s[a])<gate)a++;while(b>a&&Math.abs(s[b])<gate)b--;return s.slice(a,Math.max(a+1,b+1))};const cap=(s,sr)=>s.length>Math.floor(sr*1.8)?s.slice(0,Math.floor(sr*1.8)):s;
    const analyze=(s,sr)=>{const N=512,H=256,BINS=16,all=[];for(let off=0;off+N<=s.length;off+=H){let e=0,z=0,prev=s[off];for(let j=0;j<N;j++){const v=s[off+j];e+=v*v;if(j&&((v>=0)!=(prev>=0)))z++;prev=v}const rms=Math.sqrt(e/N);if(rms<.0018)continue;const powers=new Float64Array(BINS);for(let q=1;q<=BINS;q++){let re=0,im=0;for(let jj=0;jj<N;jj+=2){const v=s[off+jj],w=.5-.5*Math.cos(2*Math.PI*jj/(N-1)),ang=2*Math.PI*q*jj/N;re+=v*w*Math.cos(ang);im-=v*w*Math.sin(ang)}powers[q-1]=re*re+im*im+1e-12}let total=0,cent=0,low=0,mid=0,high=0,logSum=0;for(let q=0;q<BINS;q++){const p=powers[q];total+=p;cent+=(q+1)*p;logSum+=Math.log(p);if(q<3)low+=p;else if(q<8)mid+=p;else high+=p}let corr=0,bestLag=0;const lo=Math.max(2,Math.floor(sr/520)),hi=Math.min(N-2,Math.floor(sr/70));for(let lag=lo;lag<=hi;lag+=4){let c=0,a=0,b=0;for(let j=0;j<N-lag;j+=4){const u=s[off+j],v=s[off+j+lag];c+=u*v;a+=u*u;b+=v*v}const score=c/Math.sqrt((a*b)||1);if(score>corr){corr=score;bestLag=lag}}const pitch=corr>.28&&bestLag?sr/bestLag:0;all.push({rms,zcr:z/N,centroid:cent/(BINS*total),low:low/total,mid:mid/total,high:high/total,flat:Math.exp(logSum/BINS)/(total/BINS),periodic:Math.max(0,corr),pitch})}const pick=(from,to)=>{const q=all.slice(Math.floor(all.length*from),Math.max(Math.floor(all.length*to),Math.floor(all.length*from)+1));return q.length?q:all};const avg=(q,key)=>q.length?q.reduce((a,v)=>a+v[key],0)/q.length:0;const ini=pick(0,.34),whole=pick(0,1),f0=all.filter(v=>v.pitch>0).map(v=>v.pitch),median=(a)=>{const q=a.filter(Number.isFinite).sort((x,y)=>x-y);return q.length?q[Math.floor(q.length/2)]:0};let peak=0;for(const v of s)peak=Math.max(peak,Math.abs(v));return{frames:all,duration:s.length/sr,rms:Math.sqrt(s.reduce((a,v)=>a+v*v,0)/Math.max(1,s.length)),peak,initial:{zcr:avg(ini,"zcr"),centroid:avg(ini,"centroid"),low:avg(ini,"low"),mid:avg(ini,"mid"),high:avg(ini,"high"),flat:avg(ini,"flat"),periodic:avg(ini,"periodic")},whole:{zcr:avg(whole,"zcr"),centroid:avg(whole,"centroid"),low:avg(whole,"low"),mid:avg(whole,"mid"),high:avg(whole,"high"),flat:avg(whole,"flat"),periodic:avg(whole,"periodic")},f0,base:median(f0)}};
    const clamp=(v,a,z)=>Math.max(a,Math.min(z,v));
    const median=(a)=>{const q=a.filter(Number.isFinite).sort((x,y)=>x-y);return q.length?q[Math.floor(q.length/2)]:0};
    const ub=await bytes(x);if(!ub) return fail("The recording could not be read. Please record again in Chrome.");const buf=await ctx.decodeAudioData(ub),us=mono(buf),u0=basic(us,buf.sampleRate);if(u0.peak<.004||u0.rms<.00065)return fail("Speech was too faint to grade reliably. Move a little closer to the microphone and record the full syllable again.");const u=analyze(cap(trim(us,u0.peak),buf.sampleRate),buf.sampleRate);if(u.frames.length<2)return fail("Speech was detected, but there was not enough stable voice information to grade. Hold the syllable slightly longer and try again.");let r=null;if(A){const refCache=window.__PINYIN_REFERENCE_FEATURES_CACHE__||(window.__PINYIN_REFERENCE_FEATURES_CACHE__={}),refKey=String(A);if(refCache[refKey])r=refCache[refKey];else{const refBuf=await fastDecode(A,1800);if(refBuf){const rs=mono(refBuf),rb=basic(rs,refBuf.sampleRate);r=analyze(cap(trim(rs,rb.peak),refBuf.sampleRate),refBuf.sampleRate);refCache[refKey]=r}}}
    const contour=(an)=>{const base=an?.base||180,series=(an?.frames||[]).filter(v=>v.pitch>0).map(v=>12*Math.log2(Math.max(1,v.pitch)/Math.max(1,base)));const first=median(series.slice(0,Math.max(1,Math.floor(series.length*.3))))||0,mid=median(series.slice(Math.floor(series.length*.3),Math.ceil(series.length*.7)))||0,last=median(series.slice(Math.floor(series.length*.7)))||0,minPitch=series.length?Math.min(...series):0,maxPitch=series.length?Math.max(...series):0,slope=last-first,range=maxPitch-minPitch,dip=Math.max(0,Math.min(first,last)-mid),recovery=last-mid;return{base,series,first,mid,last,minPitch,maxPitch,slope,range,dip,recovery}};
    const uc=contour(u),rc=r?contour(r):null,base=uc.base,first=uc.first,mid=uc.mid,last=uc.last,slope=uc.slope,range=uc.range,dip=uc.dip,recovery=uc.recovery;
    const tone=Number(D);
    let theoretical=tone===1?clamp(1-(Math.abs(slope)*.18+Math.max(0,range-4)*.06),0,1):tone===2?clamp(.42+.24*slope+.18*(last>first+.5),0,1):tone===3?clamp(.22+.22*dip+.18*Math.max(0,recovery)+.13*(first>mid+.25)+.13*(last>mid+.35),0,1):tone===4?clamp(.42-.24*slope+.18*(first>last+.5),0,1):.25;
    let referenceToneSim=null;if(rc&&uc.series.length>=3&&rc.series.length>=3){const d=.18*Math.abs(first-rc.first)+.22*Math.abs(mid-rc.mid)+.18*Math.abs(last-rc.last)+.24*Math.abs(slope-rc.slope)+.10*Math.abs(range-rc.range)+.08*Math.abs(dip-rc.dip);referenceToneSim=clamp(1-d/4.8,0,1)}
    let toneShape=referenceToneSim==null?theoretical:clamp(.58*theoretical+.42*referenceToneSim,0,1);
    const toneDirectionWrong=tone===1?(Math.abs(slope)>2.6||range>6.5):tone===2?slope<.2:tone===3?(dip<.35||recovery<.2):tone===4?slope>-.2:false;
    const strongToneError=tone===1?(Math.abs(slope)>4||range>8):tone===2?slope<-.7:tone===3?(dip<.15&&recovery<.05):tone===4?slope>.7:false;
    if(strongToneError)toneShape=Math.min(toneShape,.23);else if(toneDirectionWrong)toneShape=Math.min(toneShape,.49);else if(referenceToneSim!=null&&referenceToneSim>.84&&theoretical>.68)toneShape=Math.max(toneShape,.86);
    const toneScore=Math.round(35*toneShape),duration=u.duration,expectedFrames=Math.max(1,Math.floor(duration*buf.sampleRate/256)),voiced=clamp(u.frames.length/expectedFrames,0,1),clarity=clamp((u.rms-.0008)/.024,0,1),periodicity=clamp(u.whole.periodic/.58,0,1),fixedDurFit=clamp(1-Math.abs(duration-.68)/.85,0,1),refDurFit=r?clamp(1-Math.abs(duration-r.duration)/Math.max(.45,r.duration*1.15),0,1):fixedDurFit,durFit=clamp(.35*fixedDurFit+.65*refDurFit,0,1),signalConfidence=clamp(.38*voiced+.32*clarity+.30*periodicity,0,1);
    const initialOf=(py)=>{const z=String(py||k||"").toLowerCase().replace(/[āáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜ]/g,"");return ["zh","ch","sh"].find(v=>z.startsWith(v))||["b","p","m","f","d","t","n","l","g","k","h","j","q","x","r","z","c","s"].find(v=>z.startsWith(v))||"zero"};
    const family=(i)=>i==="m"||i==="n"?"nasal":i==="r"||["zh","ch","sh","z","c","s","j","q","x","h"].includes(i)?"fricative":i==="f"?"labiodental":["b","p","d","t","g","k"].includes(i)?"stop":i==="l"?"lateral":i==="zero"?"zero":"other";
    const infer=(q)=>{if(q.zcr>.145&&q.centroid>.205&&q.flat>.095)return"fricative";if(q.low>.27&&q.periodic>.30&&q.centroid<.34)return"nasal";if(q.zcr<.125&&q.periodic<.47)return"stop";if(q.periodic>.52&&q.zcr<.14)return"voiced";return"unknown"};
    const targetInitial=initialOf(k),expected=family(targetInitial),observed=infer(u.initial),relation=expected==="zero"?(observed==="unknown"||observed==="zero"||observed==="voiced"?1:.18):(observed===expected?1:(observed==="unknown"||observed==="voiced"?.55:(((expected==="nasal"&&observed==="fricative")||(expected==="fricative"&&observed==="nasal"))?.08:(((expected==="stop"&&observed==="nasal")||(expected==="nasal"&&observed==="stop"))?.35:.22))));
    const dist=(a,b)=>!a||!b?1:.28*Math.abs(a.centroid-b.centroid)+.22*Math.abs(a.zcr-b.zcr)+.14*Math.abs(a.low-b.low)+.08*Math.abs(a.mid-b.mid)+.14*Math.abs(a.high-b.high)+.08*Math.abs(a.flat-b.flat)+.06*Math.abs(a.periodic-b.periodic),initialDist=r?dist(u.initial,r.initial):1,wholeDist=r?dist(u.whole,r.whole):1,spectralSim=r?clamp(1-(.72*initialDist+.28*wholeDist)*2.05,0,1):clamp(.48+.22*(relation-.5),0,1),segmentSim=r?clamp(.82*spectralSim+.18*relation,0,1):clamp(.72*relation+.18*clarity+.10*periodicity,0,1),severe=(relation<=.1&&(!r||spectralSim<.55))||(r&&spectralSim<.27)||segmentSim<.34,near=!severe&&(relation<.5||(r&&spectralSim<.68)||segmentSim<.76);let segmental=35*segmentSim;if(r&&spectralSim>.84&&relation>=.55)segmental=Math.max(segmental,30);if(severe)segmental=Math.min(segmental,8);else if(near)segmental=Math.min(segmental,24);
    const articulation=20*clamp(.15*clarity+.55*segmentSim+.20*durFit+.10*periodicity,0,1),fluency=10*clamp(.65*durFit+.35*voiced,0,1);let total=Math.round(clamp(toneScore+segmental+articulation+fluency,0,100));if(signalConfidence<.23)total=Math.min(total,45);if(severe)total=Math.min(total,34);else if(strongToneError)total=Math.min(total,39);else if(toneDirectionWrong)total=Math.min(total,55);else if(near)total=Math.min(total,74);
    const classification=severe?"Initial/final error":strongToneError||toneDirectionWrong?"Tone error — review required":signalConfidence<.23?"Signal too weak for a reliable pass":near?"Nearly correct — refine":total>=90?"Excellent":total>=80?"Good":total>=70?"Acceptable":total>=55?"Needs targeted practice":"Needs improvement";
    const toneFeedback=toneScore>=30?`The tone contour matches the target direction well${referenceToneSim!=null?" and is close to the instructor model":""}. Pitch is normalized to the speaker baseline (about ${Math.round(base)} Hz).`:toneScore>=20?"The overall contour is partly correct, but the slope, dip or recovery is not distinct enough. Slow the syllable down and copy the model contour.":"The target tone contour is not reliable yet. Rebuild the pitch direction and turning point before increasing speed.";
    const targetText=targetInitial==="zero"?"zero initial":targetInitial,obsText=observed==="unknown"?"not clear enough to identify":observed,segmentalFeedback=severe?`Clear initial/final mismatch: target ${targetText}, while the recording resembles ${obsText}. Rework tongue placement and airflow.`:near?`The initial/final is close but still differs from the instructor model. Target ${targetText}; keep the consonant release, tongue position and final quality more consistent.`:`Initial–final accuracy is close to the instructor model for target ${targetText}; maintain the same airflow, tongue placement and final quality.`;
    const articulationFeedback=articulation<14?"Articulation or tongue placement is not yet stable. Practise with a mirror and keep the consonant release and vowel shape consistent with the model.":"Articulation and syllable stability are satisfactory.",fluencyFeedback=fluency<7?"Produce the syllable in one continuous breath at a moderate rate without internal breaks.":"Fluency and speaking rhythm are stable.";
    const feedback=signalConfidence<.23?`Speech was detected, but the signal was too weak for a reliable high score — ${total}/100. Move slightly closer to the microphone and try again.`:severe?`Initial/final error — ${total}/100. Target ${k}; replay the model and practise the isolated syllable.`:strongToneError||toneDirectionWrong?`Tone error — ${total}/100. The segment may be close, but the pitch contour does not match the target.`:near?`Nearly correct — ${total}/100. The recording is understandable, but a measurable tone or segment difference remains.`:`${classification} — ${total}/100. Scored against the instructor model with speaker-normalized pitch, segmental similarity, articulation and fluency.`;
    const details=[`Tone: ${toneScore}/35 — ${toneFeedback}`,`Initial–final accuracy: ${Math.round(segmental)}/35 — ${segmentalFeedback}`,`Articulation & tongue placement: ${Math.round(articulation)}/20 — ${articulationFeedback}`,`Prosody & fluency: ${Math.round(fluency)}/10 — ${fluencyFeedback}`];await ctx.close().catch(()=>{});return{score:total,feedback,classification,toneScore,toneFeedback,segmentalScore:Math.round(segmental),segmentalFeedback,articulationScore:Math.round(articulation),articulationFeedback,fluencyScore:Math.round(fluency),fluencyFeedback,details,metrics:{duration,voicedRatio:voiced,pitchRange:range,speakerBaseHz:base,spectralSimilarity:segmentSim,referenceToneSimilarity:referenceToneSim,signalConfidence,expectedInitial:targetInitial,observedInitial:observed,gradingMs:Math.round(performance.now()-started)}};
  }catch(e){if(ctx)await ctx.close().catch(()=>{});return fail("Local recording analysis failed: "+(e&&e.message?e.message:"unknown error")+". Please record again in Chrome.")}
}