/* PanTutor AI v57.3 — explainable pedagogical planner, cached audit */
(function(){
 'use strict';
 const AUDIT_KEY='pandahan_v57_ai_decisions';
 let auditCache=null,auditTimer=0;
 function ensureAudits(){if(auditCache)return auditCache;try{const x=JSON.parse(localStorage.getItem(AUDIT_KEY)||'[]');auditCache=Array.isArray(x)?x.slice(-400):[];}catch(_){auditCache=[];}return auditCache;}
 function persistAudit(){if(auditTimer){clearTimeout(auditTimer);auditTimer=0;}try{localStorage.setItem(AUDIT_KEY,JSON.stringify(ensureAudits().slice(-400)));}catch(_){} }
 function persistAuditSoon(){clearTimeout(auditTimer);auditTimer=setTimeout(()=>{auditTimer=0;persistAudit();},250);}
 function allAudits(){return ensureAudits().slice();}
 function audit(row){try{const a=ensureAudits();const fp=[row.targetConcept||'GLOBAL',row.selectedIntervention?.action||row.intervention?.action||'',row.diagnosis?.type||row.issue?.type||'',row.diagnosis?.evidenceCount||row.issue?.evidenceCount||0].join('|');const last=a[a.length-1];if(last?.fingerprint===fp&&Date.now()-Number(last.generatedAt||0)<30000)return last;const out={...row,fingerprint:fp};a.push(out);if(a.length>400)a.splice(0,a.length-400);persistAuditSoon();return out;}catch(_){return row;}}
 function intervention(issue,concept){if(!issue)return{action:'normal_curriculum',targetSkill:'general'};if(issue.type==='SEMANTIC_CONTEXT_CONFUSION')return{action:'semantic_contrast',targetSkill:'context_use',contrastWith:issue.confusedWith};const s=issue.skill||'';if(/tone|pronunciation/.test(s))return{action:'tone_clinic',targetSkill:s};if(s==='context_use')return{action:'context_discrimination_then_production',targetSkill:s};if(s==='production'||s==='writing')return{action:'scaffolded_production',targetSkill:s};if(s==='component_reasoning')return{action:'character_reasoning',targetSkill:s};if(s==='transfer')return{action:'novel_character_transfer',targetSkill:s};if(s==='meaning'||s==='recognition')return{action:'retrieval_practice',targetSkill:s};return{action:'targeted_review',targetSkill:s||'general'};}
 function strategyFor(it){const best=window.PandaHanStrategyModel?.best?.(2)||null;if(!best)return null;const compatible={semantic_contrast:['contrastive_context','retrieval_practice'],context_discrimination_then_production:['contrastive_context','scaffolded_production'],scaffolded_production:['scaffolded_production'],tone_clinic:['tone_discrimination'],character_reasoning:['semantic_component_reasoning','self_generated_reasoning'],novel_character_transfer:['transfer_reasoning','semantic_component_reasoning'],retrieval_practice:['retrieval_practice']}[it?.action]||[];return compatible.includes(best.strategy)?best:null;}
 function planForConcept(concept,opts={}){const d=window.PandaHanDiagnostic?.diagnoseConcept?.(concept)||{issues:[]};const issue=(d.issues||[]).find(x=>x.type==='SEMANTIC_CONTEXT_CONFUSION')||d.issues?.[0]||null;const it=intervention(issue,concept);const strategy=strategyFor(it);const reason=[];if(issue){reason.push(`${issue.type}${issue.skill?` · ${issue.skill}`:''}`);if(issue.confusedWith)reason.push(`recent confusion with ${issue.confusedWith}`);reason.push(`${issue.evidenceCount||d.evidenceCount} supporting evidence item(s)`);}else reason.push('no persistent weakness detected; continue curriculum');if(strategy)reason.push(`learner outcome history also supports ${strategy.strategy}`);const row={decisionId:`DEC-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,targetConcept:String(concept||''),diagnosis:issue,selectedIntervention:it,strategySuggestion:strategy?{strategy:strategy.strategy,utility:strategy.estimate,confidence:strategy.confidence,evidenceCount:strategy.n}:null,whyConcept:issue?'Recent evidence indicates this concept needs targeted support.':'This concept follows the current learning/review path.',whyActivity:issue?`The selected activity targets ${it.targetSkill||'the observed weakness'} instead of repeating unrelated practice.`:'No targeted intervention is needed.',whyNow:d.evidenceCount?`Decision is based on ${d.evidenceCount} recent evidence item(s).`:'Not enough evidence for a stronger adaptation.',confidence:d.confidence||0,reason,generatedAt:Date.now(),modelVersion:'PanTutor-PED-57.3'};if(opts.audit!==false)audit(row);return row;}
 function nextGlobal(opts={}){const g=window.PandaHanDiagnostic?.diagnoseGlobal?.()||{issues:[]};const issue=g.issues?.[0];const it=issue?intervention(issue,''):{action:'normal_curriculum',targetSkill:'general'};const strategy=strategyFor(it);const row=issue?{decisionId:`GLOBAL-${Date.now()}`,focus:issue.skill,intervention:it,strategySuggestion:strategy?{strategy:strategy.strategy,utility:strategy.estimate,confidence:strategy.confidence,evidenceCount:strategy.n}:null,why:`${issue.skill} is currently the weakest repeatedly observed skill.`,issue,generatedAt:Date.now(),modelVersion:'PanTutor-PED-57.3'}:{decisionId:`GLOBAL-${Date.now()}`,focus:'core_curriculum',intervention:{action:'normal_curriculum'},why:'No repeated weakness has enough evidence yet.',generatedAt:Date.now(),modelVersion:'PanTutor-PED-57.3'};if(opts.audit!==false)audit({targetConcept:'',selectedIntervention:row.intervention,diagnosis:row.issue||null,...row});return row;}
 window.addEventListener('pagehide',persistAudit);
 window.PandaHanPedagogy={planForConcept,nextGlobal,intervention,allAudits,flushAudit:persistAudit,version:'57.3'};
})();
